export const INITIAL_SEASON = '2024';
export const EMPTY_ERROR = {
  type: '',
  message: '',
};

export const EMPTY_EVENT_DATA: EventSchedule = {
  RoundNumber: 0,
  Country: '',
  Location: '',
  OfficialEventName: '',
  EventDate: '',
  EventName: '',
  EventFormat: '',
  Session1: '',
  Session1Date: '',
  Session1DateUtc: '',
  Session2: '',
  Session2Date: '',
  Session2DateUtc: '',
  Session3: '',
  Session3Date: '',
  Session3DateUtc: '',
  Session4: '',
  Session4Date: '',
  Session4DateUtc: '',
  Session5: '',
  Session5Date: '',
  Session5DateUtc: '',
  F1ApiSupport: false,
};
export const DEFAULT_SESSION_DATA: SessionBasics = {
  index: 5,
  name: 'Race',
  date: '',
  dateUtc: '',
};
export const EMPTY_DRIVER_DATA: DriverResult = {
  DriverNumber: '',
  BroadcastName: '',
  Abbreviation: '',
  DriverId: '',
  TeamName: '',
  TeamColor: '',
  TeamId: '',
  FirstName: '',
  LastName: '',
  FullName: '',
  HeadshotUrl: '',
  CountryCode: '',
  Position: 0,
  ClassifiedPosition: '',
  GridPosition: 0,
  Q1: null,
  Q2: null,
  Q3: null,
  Time: null,
  Status: '',
  Points: 0,
};
